{{- if not .Values.protonpass.auth.existingSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protonpass-eso-provider.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "protonpass-eso-provider.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.protonpass.auth.existingSecret.usernameKey | default "username" }}: {{ .Values.protonpass.auth.credentials.username | quote }}
  {{ .Values.protonpass.auth.existingSecret.passwordKey | default "password" }}: {{ .Values.protonpass.auth.credentials.password | quote }}
{{- end }}
---
{{- if not .Values.api.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protonpass-eso-provider.fullname" . }}-api-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "protonpass-eso-provider.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.existingSecret.key | default "token" }}: {{ .Values.api.token | default (randAlphaNum 32) | quote }}
{{- end }}
