{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.externalSecret.target.name }}
    template:
      type: Opaque
  data:
    {{- range $key, $val := .Values.externalSecret.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $val.remoteRef.key | quote }}
        property: {{ $val.remoteRef.property | quote }}
    {{- end }}
{{- end }}
